#! /bin/bash
tar cvfz kupdate.tgz k*.cc first.cc index.cc input_lexer.ll input_lexer.cc lexer.h.bak input_parser.yy input_parser.cc Makefile *.h *.ld *.bmp *.hpp *.cpp console.cc main.cc iostream.new iostream mkgiac mkxcas mkfr mken updatecasio *.png
#scp kupdate.tgz malherbe.ujf-grenoble.fr:tmp
